language: java
jdk:
  - openjdk11

sudo: required
services:
  - docker

jobs:
  include:
    - stage: build
      script: "./gradlew clean spock-geb-quickstart:build -i --stacktrace -Pprofile=docker"
