language: java
jdk:
  - openjdk11

sudo: required
services:
  - docker

jobs:
  include:
    - stage: build
      script: "./gradlew clean spock-geb-quickstart:build spock-geb-quickstart:dIT -i --stacktrace -Dspring.profiles.active=docker"
